### PR TITLE
`rect` needs to be integers

### PR DESCRIPTION
**Pull request by Francismori7**
Added Math.round to make sure we provide integers to the Sanity API.

### CODE REVIEW

**Comment by coreyward** [comment]
Hi! This code change does not produce any difference in behavior from what I can tell. 

- The `width` and `height` variables are already `number` types
- They've already been `Math.round`ed in `croppedImageSize`, which is confirmed by the tests
- The function returns a string parameter, and all query _string_ parameters and values are strings (the receiving application has to parse them and can opt to cast them to any type they like)

Here are the tests for the function, for reference:

https://github.com/coreyward/sanity-image/blob/3ba62840bf908c54774c256f75f314c7c9d81298/src/urlBuilder.test.ts#L585-L621

If I've missed something, please try to contribute a test that would be failing without the change, or at least provide example inputs. Thank you! 🙏

**Comment by Francismori7** [comment]
Hey Corey,

At this moment, it generates this:
```
<img data-loading="true" style="height:10px !important;opacity:0;pointer-events:none;position:absolute;user-select:none;width:10px !important;z-index:-10" alt="Living room d'une maison" loading="lazy" sizes="(max-width: 1024px) 100vw, (max-width: 1280px) 35vw, 400px" class="h-full w-full object-cover" srcset="https://cdn.sanity.io/images/uaaz0vqb/production/0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,113.77165999070529,8170,5027&w=200 200w, https://cdn.sanity.io/images/uaaz0vqb/production/0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,113.77165999070529,8170,5027&w=400 400w, https://cdn.sanity.io/images/uaaz0vqb/production/0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,113.77165999070529,8170,5027&w=600 600w, https://cdn.sanity.io/images/uaaz0vqb/production/0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,113.77165999070529,8170,5027&w=800 800w" src="https://cdn.sanity.io/images/uaaz0vqb/production/0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,113.77165999070529,8170,5027&w=400" width="400" height="246">
```

As you can see, it sets 113.77165999070529 for rect value index 1.

And, in turn, Sanity responds with: 
image

**Comment by coreyward** [comment]
That's the second value in the array (the `top` value) anyways. Are you still on the alpha version? If so, go ahead and update, and be aware that the props changed significantly between the alpha and stable versions. If not, can you please provide the input params (particularly the image ID, requested dimensions, mode, and the crop values)?

**Comment by Francismori7** [comment]
I am on 0.1.1 and migrated the changes in the props.

Code that is used is as follows:
```
<a>
  <SanityImage
    id={images[5].image.id}
    hotspot={images[5].image.hotspot}
    crop={images[5].image.crop}
    preview={images[5].image.preview}
    {...imageConfig}
    width={400}
    alt={images[5].label}
    sizes="(max-width: 1024px) 100vw, (max-width: 1280px) 35vw, 400px"
    className="h-full w-full object-cover"
  />
</a>
```

Here is the output:
```<a href="#">Living room d'une maisonLiving room d'une maison</a>```

The object that is used does have floating points, as expected from the Sanity API (pulled via GROQ)
```
{
    "_type": "image",
    "asset": {
        "_ref": "image-0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141-jpg",
        "_type": "reference"
    },
    "crop": {
        "_type": "sanity.imageCrop",
        "bottom": 0,
        "left": 0,
        "right": 0.015410958904109595,
        "top": 0.022130258702724233
    },
    "hotspot": {
        "_type": "sanity.imageHotspot",
        "height": 0.38588532099940226,
        "width": 0.1986301369863011,
        "x": 0.8852739726027399,
        "y": 0.5359616703919268
    },
    "id": "image-0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141-jpg",
    "preview": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAMABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAYIAf/EACIQAAEDAgcBAQAAAAAAAAAAAAECAwQABQYHERIUITEyYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGhEAAwADAQAAAAAAAAAAAAAAAAECERJBUf/aAAwDAQACEQMRAD8AcLBm1ZLnNTHLpY193kaUxu46wy9I47VxQHAO1BWgqKYlwfAChtB8+a2bd5aVBKVgD8FFUuIFHpW07MbDjElTfOCynolPlFRwqY8oklXZoqMl6o//2Q=="
}
```

**Comment by coreyward** [comment]
I built out a test case with your input locally and it seems to be working as expected. I don't know what you have in `imageConfig`, but I wonder if you don't have a cached value from an alpha build or similar.

```jsx
it("should use rounted rect values", () => {
  const { baseElement } = render(
    <SanityImage
      baseUrl="https://cdn.sanity.io/images/abc123/production"
      id="image-0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141-jpg"
      hotspot={{
        x: 0.8852739726027399,
        y: 0.5359616703919268,
      }}
      crop={{
        bottom: 0,
        left: 0,
        right: 0.015410958904109595,
        top: 0.022130258702724233,
      }}
      preview="data:image/jpeg;base64,abc123"
      width={400}
      alt="alt text"
      sizes="(max-width: 1024px) 100vw, (max-width: 1280px) 35vw, 400px"
      className="h-full w-full object-cover"
    />
  )

  expect(baseElement).toMatchInlineSnapshot(`
    <body>
      <div>
        <img
          alt="alt text"
          class="h-full w-full object-cover"
          data-lqip="true"
          height="246"
          src="data:image/jpeg;base64,abc123"
          width="400"
        />
        <img
          alt="alt text"
          class="h-full w-full object-cover"
          data-loading="true"
          height="246"
          loading="lazy"
          sizes="(max-width: 1024px) 100vw, (max-width: 1280px) 35vw, 400px"
          src="https://cdn.sanity.io/images/abc123/production0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,114,8170,5027&w=400"
          srcset="https://cdn.sanity.io/images/abc123/production0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,114,8170,5027&w=200 200w, https://cdn.sanity.io/images/abc123/production0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,114,8170,5027&w=400 400w, https://cdn.sanity.io/images/abc123/production0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,114,8170,5027&w=600 600w, https://cdn.sanity.io/images/abc123/production0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141.jpg?auto=format&fit=max&q=75&rect=0,114,8170,5027&w=800 800w"
          style="opacity: 0; pointer-events: none; position: absolute; user-select: none; z-index: -10;"
          width="400"
        />
      </div>
    </body>
  `)
})
```

Similarly, a test for `buildRect` with the relevant input params produces the expected rounded output values:

```ts
it("rounds crop rect values", () => {
  expect(
    buildQueryParams({
      crop: {
        bottom: 0,
        left: 0,
        right: 0.015410958904109595,
        top: 0.022130258702724233,
      },
      hotspot: {
        x: 0.8852739726027399,
        y: 0.5359616703919268,
      },
      id: "image-0a9787c625d9616d59a1a706cd8235fe624f3976-8298x5141-jpg",
    })
  ).toEqual(<ImageQueryParams>{
    auto: "format",
    fit: "max",
    q: 75,
    rect: "0,114,8170,5027",
    w: 4085,
  })
})
```

**Comment by Francismori7** [comment]
This is very weird, imageConfig only has projectId and dataset.
Maybe that works differently than from baseUrl?

Francis Morissette

**Comment by coreyward** [comment]
Very strange indeed. The `dataset` and `projectId` are applied pretty simply:

https://github.com/coreyward/sanity-image/blob/319e381989ef3994fd5832589e56924cb0d75a3e/src/SanityImage.tsx#L46

If you `import { buildSrc } from 'sanity-image'` and pass it the [relevant params](https://github.com/coreyward/sanity-image/blob/319e381989ef3994fd5832589e56924cb0d75a3e/src/types.ts#L138-L176) (note: no preview, alt, etc), what do you get back?

Long shot, but any chance `Math.round` has been redefined?

**Comment by coreyward** [comment]
Oh, I know what the issue is. I hadn't published the rect rounding change. 🤦‍♂️ 

If you update to `v0.1.2` you should be good to go. Sorry for the goose chase!

**Comment by Francismori7** [comment]
That indeed fixed it ;)!

Thanks.

**Pull request closed without merging**
